import { detectSchema } from './connectorService';

/**
 * Fetch schema for a connector
 * Prioritizes manual schema if available, falls back to auto-detection
 * @param {string} connectorId - Connector ID
 * @returns {Promise<Object>} Schema object with standardized format
 */
export async function fetchSchema(connectorId) {
  // First, try to get the connector to check for manual schema
  const { fetchConnectorById } = await import('./connectorService');
  const connector = await fetchConnectorById(connectorId);

  // If manual schema exists, use it
  // Check if schema has fields array (either with isManual flag or just fields)
  if (connector.schema && connector.schema.fields && Array.isArray(connector.schema.fields) && connector.schema.fields.length > 0) {
    return {
      fields: connector.schema.fields,
      isManual: connector.schema.isManual !== false, // Default to true if not specified
      version: connector.schema.version || 1
    };
  }

  // Otherwise, fall back to auto-detection
  const schema = await detectSchema(connectorId);

  // Transform to standardized format
  // Handle different schema structures (tables, columns, endpoints)
  let fields = [];

  if (schema.tables && schema.tables.length > 0) {
    // Database schema with tables
    // Fields that should never be required (auto-generated or system fields)
    const autoGeneratedFields = ['id', 'createdat', 'updatedat', 'created_at', 'updated_at'];

    fields = schema.tables[0].columns.map(col => {
      const isAutoGenerated = autoGeneratedFields.includes(col.name.toLowerCase());
      return {
        name: col.name,
        type: col.type,
        nullable: col.nullable !== false,
        required: !isAutoGenerated && col.nullable === false,
        description: col.description || ''
      };
    });
  } else if (schema.columns) {
    // File schema with columns
    fields = schema.columns.map(col => ({
      name: col.name,
      type: col.type || 'varchar',
      nullable: true,
      required: false,
      description: ''
    }));
  } else if (schema.endpoints) {
    // API schema with endpoints
    // Use first endpoint's fields
    const firstEndpoint = schema.endpoints[0];
    fields = (firstEndpoint.fields || []).map(fieldName => ({
      name: fieldName,
      type: 'varchar',
      nullable: true,
      required: false,
      description: ''
    }));
  }

  return {
    fields,
    isManual: false // Indicate this was auto-detected
  };
}

/**
 * Save manual schema for a connector
 * @param {string} connectorId - Connector ID
 * @param {Array} fields - Field definitions
 * @returns {Promise<Object>} Saved schema
 */
export async function saveSchema(connectorId, fields) {
  const { fetchConnectorById, saveConnector } = await import('./connectorService');
  const connector = await fetchConnectorById(connectorId);

  // Update connector with manual schema
  const updatedConnector = {
    ...connector,
    schema: {
      fields,
      version: (connector.schema?.version || 0) + 1,
      isManual: true,
      lastModified: new Date().toISOString()
    }
  };

  await saveConnector(updatedConnector);

  return updatedConnector.schema;
}

/**
 * Validate schema definition
 * @param {Array} fields - Field definitions to validate
 * @returns {Object} Validation result
 */
export function validateSchema(fields) {
  const errors = [];

  // Check if at least one field is defined
  if (!fields || fields.length === 0) {
    errors.push('At least one field must be defined');
    return { isValid: false, errors };
  }

  // Check for exactly one unique identifier
  const uniqueIdentifiers = fields.filter(f => f.isPrimaryKey || f.isUnique);
  if (uniqueIdentifiers.length === 0) {
    errors.push('Exactly one field must be marked as a unique identifier');
  } else if (uniqueIdentifiers.length > 1) {
    errors.push(`Only one field can be marked as a unique identifier. Currently marked: ${uniqueIdentifiers.map(f => f.name).join(', ')}`);
  }

  // Check that unique identifier is also required
  uniqueIdentifiers.forEach(field => {
    if (!field.required) {
      errors.push(`Unique identifier '${field.name}' must be marked as required`);
    }
  });

  // Check for duplicate field names
  const fieldNames = fields
    .filter(f => f && f.name) // Filter out fields without names
    .map(f => f.name.toLowerCase());
  const duplicates = fieldNames.filter((name, index) => fieldNames.indexOf(name) !== index);
  const uniqueDuplicates = [...new Set(duplicates)];

  uniqueDuplicates.forEach(name => {
    errors.push(`Duplicate field name: '${name}'`);
  });

  // Validate each field
  fields.forEach((field, index) => {
    const fieldNum = index + 1;

    // Check field name
    if (!field.name || field.name.trim() === '') {
      errors.push(`Field ${fieldNum}: Name is required`);
    } else if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(field.name)) {
      errors.push(`Field ${fieldNum}: Name '${field.name}' contains invalid characters. Use only letters, numbers, and underscores.`);
    }

    // Check data type
    if (!field.type || field.type.trim() === '') {
      errors.push(`Field ${fieldNum}: Data type is required`);
    }

    // Check Required and Nullable conflict
    if (field.required && field.nullable) {
      errors.push(`Field ${fieldNum} ('${field.name}'): Cannot be both Required and Nullable`);
    }
  });

  return {
    isValid: errors.length === 0,
    errors
  };
}

/**
 * Generate auto-mapping suggestions based on field names
 * @param {Object} sourceSchema - Source schema
 * @param {Object} destinationSchema - Destination schema
 * @returns {Array} Suggested mappings
 */
export function generateMappingSuggestions(sourceSchema, destinationSchema) {
  const suggestions = [];

  destinationSchema.fields.forEach(destField => {
    // Exact match (case-insensitive)
    const exactMatch = sourceSchema.fields.find(
      sf => sf.name.toLowerCase() === destField.name.toLowerCase()
    );

    if (exactMatch) {
      suggestions.push({
        id: `suggestion-${Date.now()}-${Math.random()}`,
        sourceFields: [exactMatch.name],
        destinationField: destField.name,
        transformationId: null,
        transformationConfig: null,
        confidence: 'high',
        reason: 'Exact name match',
        order: suggestions.length + 1
      });
      return;
    }

    // Fuzzy match (similar names)
    const fuzzyMatches = sourceSchema.fields
      .map(sf => ({
        field: sf,
        similarity: stringSimilarity(sf.name, destField.name)
      }))
      .filter(match => match.similarity > 0.7)
      .sort((a, b) => b.similarity - a.similarity);

    if (fuzzyMatches.length > 0) {
      const bestMatch = fuzzyMatches[0];
      suggestions.push({
        id: `suggestion-${Date.now()}-${Math.random()}`,
        sourceFields: [bestMatch.field.name],
        destinationField: destField.name,
        transformationId: null,
        transformationConfig: null,
        confidence: 'medium',
        reason: `Similar to ${bestMatch.field.name}`,
        order: suggestions.length + 1
      });
    }
  });

  return suggestions;
}

/**
 * Validate field mappings
 * @param {Array} mappings - Field mappings
 * @param {Object} sourceSchema - Source schema
 * @param {Object} destinationSchema - Destination schema
 * @param {Array} transformations - Available transformations
 * @returns {Object} Validation result
 */
export function validateFieldMappings(mappings, sourceSchema, destinationSchema, transformations = []) {
  const errors = [];
  const warnings = [];

  // Check that unique identifiers are mapped
  const sourceUniqueId = sourceSchema.fields.find(f => f.isPrimaryKey);
  const destUniqueId = destinationSchema.fields.find(f => f.isPrimaryKey);

  if (sourceUniqueId && destUniqueId) {
    // Check if source unique identifier is mapped to destination unique identifier
    const uniqueIdMapping = mappings.find(m =>
      m.destinationField === destUniqueId.name &&
      m.sourceFields.includes(sourceUniqueId.name)
    );

    if (!uniqueIdMapping) {
      errors.push(
        `Unique identifier mapping required: Source '${sourceUniqueId.name}' must be mapped to destination '${destUniqueId.name}'`
      );
    }
  } else {
    if (!sourceUniqueId) {
      errors.push('Source schema must have a unique identifier field defined');
    }
    if (!destUniqueId) {
      errors.push('Destination schema must have a unique identifier field defined');
    }
  }

  // Check all required destination fields are mapped
  const mappedDestFields = mappings.map(m => m.destinationField);
  const requiredFields = destinationSchema.fields.filter(f => f.required);

  requiredFields.forEach(field => {
    if (!mappedDestFields.includes(field.name)) {
      errors.push(`Required field '${field.name}' is not mapped`);
    }
  });

  // Check for duplicate destination mappings
  const duplicates = mappedDestFields.filter((item, index) =>
    mappedDestFields.indexOf(item) !== index
  );

  const uniqueDuplicates = [...new Set(duplicates)];
  uniqueDuplicates.forEach(field => {
    errors.push(`Field '${field}' is mapped multiple times`);
  });

  // Validate each mapping
  mappings.forEach((mapping, index) => {
    const mappingNum = index + 1;

    // Check source fields exist
    mapping.sourceFields.forEach(sf => {
      if (!sourceSchema.fields.find(f => f.name === sf)) {
        errors.push(`Mapping ${mappingNum}: Source field '${sf}' does not exist`);
      }
    });

    // Check destination field exists
    const destField = destinationSchema.fields.find(f => f.name === mapping.destinationField);
    if (!destField) {
      errors.push(`Mapping ${mappingNum}: Destination field '${mapping.destinationField}' does not exist`);
      return;
    }

    // Validate transformations if present
    // Support both inline transformations (with type) and referenced transformations (with transformationId)
    const hasValidTransformations = mapping.transformations &&
      mapping.transformations.length > 0 &&
      mapping.transformations.some(t => t.transformationId || t.type);

    if (hasValidTransformations) {
      // Validate each transformation in the chain
      mapping.transformations.forEach((transMapping, tIndex) => {
        // For referenced transformations, check if they exist
        if (transMapping.transformationId) {
          const trans = transformations.find(t => t.id === transMapping.transformationId);
          if (!trans) {
            errors.push(`Mapping ${mappingNum}: Transformation ${tIndex + 1} not found`);
          }
        }
        // Inline transformations with 'type' are valid as-is
      });
    } else {
      // No transformation - check constraints
      if (mapping.sourceFields.length > 1) {
        errors.push(`Mapping ${mappingNum}: Multiple source fields require a transformation`);
      } else if (mapping.sourceFields.length === 1) {
        // Check data type compatibility
        const sourceField = sourceSchema.fields.find(f => f.name === mapping.sourceFields[0]);

        if (sourceField && destField && !isTypeCompatible(sourceField.type, destField.type)) {
          errors.push(
            `Mapping ${mappingNum}: Incompatible types - cannot map ${sourceField.type} to ${destField.type}. ` +
            `Add a transformation to convert the data type.`
          );
        }
      }
    }
  });

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
    unmappedRequiredFields: requiredFields
      .filter(f => !mappedDestFields.includes(f.name))
      .map(f => f.name)
  };
}

/**
 * Check if source type is compatible with destination type
 * @param {string} sourceType - Source data type
 * @param {string} destType - Destination data type
 * @returns {boolean} True if compatible
 */
function isTypeCompatible(sourceType, destType) {
  // Simplified type compatibility check
  const typeMap = {
    'int': ['int', 'bigint', 'decimal', 'varchar', 'nvarchar', 'text'],
    'bigint': ['bigint', 'decimal', 'varchar', 'nvarchar', 'text'],
    'decimal': ['decimal', 'varchar', 'nvarchar', 'text'],
    'varchar': ['varchar', 'nvarchar', 'text'],
    'nvarchar': ['nvarchar', 'text'],
    'text': ['text'],
    'datetime': ['datetime', 'timestamp', 'varchar', 'nvarchar', 'text'],
    'timestamp': ['timestamp', 'datetime', 'varchar', 'nvarchar', 'text'],
    'boolean': ['boolean', 'int', 'varchar', 'nvarchar', 'text']
  };

  // Extract base type (remove size specifications like varchar(255))
  const sourceBase = sourceType.split('(')[0].toLowerCase().trim();
  const destBase = destType.split('(')[0].toLowerCase().trim();

  // Exact match
  if (sourceBase === destBase) return true;

  // Check compatibility map
  return typeMap[sourceBase]?.includes(destBase) || false;
}

/**
 * Calculate string similarity using Levenshtein distance
 * @param {string} s1 - First string
 * @param {string} s2 - Second string
 * @returns {number} Similarity score (0-1)
 */
function stringSimilarity(s1, s2) {
  const longer = s1.length > s2.length ? s1.toLowerCase() : s2.toLowerCase();
  const shorter = s1.length > s2.length ? s2.toLowerCase() : s1.toLowerCase();

  if (longer.length === 0) return 1.0;

  const editDistance = levenshteinDistance(longer, shorter);
  return (longer.length - editDistance) / longer.length;
}

/**
 * Calculate Levenshtein distance between two strings
 * @param {string} s1 - First string
 * @param {string} s2 - Second string
 * @returns {number} Edit distance
 */
function levenshteinDistance(s1, s2) {
  const costs = [];
  for (let i = 0; i <= s1.length; i++) {
    let lastValue = i;
    for (let j = 0; j <= s2.length; j++) {
      if (i === 0) {
        costs[j] = j;
      } else if (j > 0) {
        let newValue = costs[j - 1];
        if (s1.charAt(i - 1) !== s2.charAt(j - 1)) {
          newValue = Math.min(Math.min(newValue, lastValue), costs[j]) + 1;
        }
        costs[j - 1] = lastValue;
        lastValue = newValue;
      }
    }
    if (i > 0) costs[s2.length] = lastValue;
  }
  return costs[s2.length];
}

/**
 * Get unmapped required destination fields
 * @param {Array} mappings - Current field mappings
 * @param {Object} destinationSchema - Destination schema
 * @returns {Array} List of unmapped required field names
 */
export function getUnmappedRequiredFields(mappings, destinationSchema) {
  const mappedDestFields = mappings.map(m => m.destinationField);
  const requiredFields = destinationSchema.fields.filter(f => f.required);

  return requiredFields
    .filter(f => !mappedDestFields.includes(f.name))
    .map(f => f.name);
}

/**
 * Filter transformations compatible with given source and destination fields
 * @param {Array} transformations - All available transformations
 * @param {Array} sourceFields - Selected source fields
 * @param {Object} destinationField - Selected destination field
 * @param {Object} sourceSchema - Source schema
 * @param {Object} destinationSchema - Destination schema
 * @returns {Array} Compatible transformations
 */
export function getCompatibleTransformations(
  transformations,
  sourceFields,
  destinationField,
  sourceSchema,
  destinationSchema
) {
  if (!sourceFields || sourceFields.length === 0 || !destinationField) {
    return [];
  }

  // Return all transformations for now
  // Most transformations can work with any number of inputs
  // Only Map type transformations specifically need multiple inputs
  return transformations.filter(trans => {
    // Map transformations work best with multiple fields
    if (trans.type === 'Map' && sourceFields.length < 2) {
      return false;
    }

    // All other transformations are compatible
    return true;
  });
}

