name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'DotNetTitan'
        reponame: 'MultiTenantETL.Vue'
        token: ${{ secrets.GITHUB_TOKEN }}